//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCapplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public string Cust_Name { get; set; }
        public Nullable<long> Contact { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public Nullable<int> citycode { get; set; }
    }
}
