//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCapplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class testdemoEntities : DbContext
    {
        public testdemoEntities()
            : base("name=testdemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<tblDatabaseServer> tblDatabaseServers { get; set; }
        public virtual DbSet<tblService> tblServices { get; set; }
        public virtual DbSet<Login1> Login1 { get; set; }
        public virtual DbSet<tblDevice> tblDevices { get; set; }
    
        public virtual ObjectResult<sp_city_Result> sp_city()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_city_Result>("sp_city");
        }
    
        public virtual ObjectResult<sp_devices_Result> sp_devices()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_devices_Result>("sp_devices");
        }
    }
}
