//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCapplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDatabaseServer
    {
        public string DataSourceId { get; set; }
        public string SrcDeviceId { get; set; }
        public string SrcId { get; set; }
        public string InstallLocation { get; set; }
        public string ProductName { get; set; }
        public string Version { get; set; }
        public string Edition { get; set; }
        public string ServicePack { get; set; }
        public Nullable<bool> IsIntegratedSecurity { get; set; }
        public string DataPath { get; set; }
        public string ServiceName { get; set; }
        public string State { get; set; }
        public string StartMode { get; set; }
        public Nullable<bool> Clustered { get; set; }
        public string InstanceId { get; set; }
        public string InstanceName { get; set; }
        public string Sku { get; set; }
        public Nullable<int> SqlServiceType { get; set; }
        public string Environment { get; set; }
        public string Isv { get; set; }
        public Nullable<int> Id { get; set; }
    }
}
