//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCapplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblService
    {
        public string DataSourceId { get; set; }
        public string SrcDeviceId { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public string InstallLocation { get; set; }
        public string Account { get; set; }
        public Nullable<bool> Started { get; set; }
        public string StartMode { get; set; }
        public string Status { get; set; }
    }
}
